// DRP Lesson Content Data
// All 20 lessons across 5 paths

export type Lesson = {
  slug: string
  title: string
  duration: string
  reward: string
  xp: number
  level: number
  description: string
  prevSlug?: string
  nextSlug?: string
  content: string
  quiz: {
    questions: Array<{
      id: string
      text: string
      options: string[]
      correct: number
      explanation: string
    }>
  }
}

export const LESSONS: Record<string, Lesson> = {
  'what-is-blockchain': {
    slug: 'what-is-blockchain', title: 'What is Blockchain?',
    duration: '25m', reward: '20', xp: 40, level: 1,
    description: 'Master the fundamentals of blockchain technology — the foundation of DRP.',
    nextSlug: 'cryptography-and-hashing',
    content: `## Overview\n\nBlockchain is a distributed ledger technology that has transformed how we think about trust, transparency, and decentralized systems. At its core, a blockchain is a continuously growing list of records (blocks) linked together using cryptography — creating an immutable chain that no single entity controls.\n\n## Why It Matters for DRP\n\nUnderstanding blockchain is fundamental to grasping how the Decentralized Rights Protocol works. DRP uses blockchain to:\n\n- **Verify human activity** through Proof of Activity (PoAT)\n- **Confirm rights status** through Proof of Status (PoST)\n- **Enable trustless governance** with the Elder Quorum System\n- **Store immutable evidence** of rights violations and verifications\n\n## The Block Structure\n\nEach block contains three essential components: a **header** (previous hash, timestamp, nonce), **transaction data** (the actual records), and its own **hash** — a unique fingerprint derived from its contents.\n\n\`\`\`\nBlock 1 (Genesis) → Block 2 → Block 3 → Block N\n  Hash: abc123      Prev: abc123  Prev: def456\n\`\`\`\n\n### The Chain: How Blocks Link\n\nEach block references the **hash of the previous block**. If someone tampers with any block, its hash changes — immediately breaking the chain and signaling fraud to the entire network.\n\n## Distributed Network\n\nBlockchain runs on a peer-to-peer network of nodes. Every node holds a full copy of the chain. To add a new block, most nodes must reach agreement — this is called **consensus**.\n\nDRP uses a hybrid consensus combining:\n1. AI-weighted Elder votes (Proof of Status)\n2. Verified activity scores (Proof of Activity)\n3. Quantum-safe signatures (CRYSTALS-Dilithium)\n\n## Key Properties\n\n| Property | Description |\n|---|---|\n| **Immutability** | Data cannot be changed once confirmed |\n| **Transparency** | All participants can verify transactions |\n| **Decentralization** | No single point of failure or control |\n| **Trustlessness** | No need to trust any central authority |\n\n## Checkpoint\n\nBefore moving on, ensure you understand:\n- What a block contains (header + transactions + hash)\n- How blocks link via previous hash references\n- Why no single party can alter the blockchain\n- How DRP uses blockchain for rights verification`,
    quiz: { questions: [
      { id: 'q1', text: 'What links one block to the next in a blockchain?', options: ['A timestamp', 'The previous block\'s hash', 'A digital signature', 'A node ID'], correct: 1, explanation: 'Each block stores the hash of the previous block. This is what creates the "chain" — change any block and its hash changes, breaking the link.' },
      { id: 'q2', text: 'Which is NOT a core property of blockchain?', options: ['Immutability', 'Centralization', 'Transparency', 'Decentralization'], correct: 1, explanation: 'Centralization is the opposite of what blockchain provides. Blockchain is inherently decentralized — no single entity controls it.' },
      { id: 'q3', text: 'What is DRP\'s Proof of Activity (PoAT) used for?', options: ['Mining new tokens', 'Verifying human activity on-chain', 'Paying validator fees', 'Encrypting transactions'], correct: 1, explanation: 'Proof of Activity (PoAT) is DRP\'s unique mechanism for verifying that humans are doing real-world activities, recorded immutably on-chain.' },
    ]}
  },
  'cryptography-and-hashing': {
    slug: 'cryptography-and-hashing', title: 'Cryptography & Hashing',
    duration: '20m', reward: '15', xp: 30, level: 1,
    description: 'Understand the cryptographic primitives powering DRP — including post-quantum security.',
    prevSlug: 'what-is-blockchain', nextSlug: 'consensus-mechanisms',
    content: `## Why Cryptography Matters\n\nEvery secure blockchain — including DRP — relies on cryptography to guarantee data integrity, authenticate identities, and protect privacy. DRP goes further using **post-quantum cryptography** to remain secure even against quantum computers.\n\n## Hash Functions\n\nA hash function takes any input and produces a fixed-size output. The magic: even a tiny input change produces a completely different output.\n\n\`\`\`\n"Hello DRP"  →  SHA3-256  →  "a1b2c3d4..."\n"hello drp"  →  SHA3-256  →  "f9e8d7c6..."  ← completely different!\n\`\`\`\n\n**Properties of good hash functions:**\n- Deterministic: same input always gives same output\n- Avalanche effect: tiny change = completely different hash\n- Collision resistant: nearly impossible to find two inputs with same hash\n- One-way: cannot reverse a hash to find the original input\n\n## Digital Signatures\n\nDigital signatures prove a message was created by a specific party without revealing their private key:\n\n\`\`\`\n[Private Key + Message] → Sign → [Signature]\n[Public Key + Signature] → Verify → Valid ✓ or Invalid ✗\n\`\`\`\n\n## Post-Quantum Cryptography in DRP\n\nStandard algorithms (RSA, ECDSA) can be broken by quantum computers. DRP is quantum-ready:\n\n| Algorithm | Purpose |\n|---|---|\n| CRYSTALS-Kyber | Key encapsulation / secure key exchange |\n| CRYSTALS-Dilithium | Digital signatures for transactions |\n| SHA3-256 | Hashing (quantum-resistant by design) |\n\nThis ensures DRP rights records remain secure for decades.`,
    quiz: { questions: [
      { id: 'q1', text: 'What is the "avalanche effect" in hashing?', options: ['Hashing is slow for large files', 'A small input change causes a completely different hash', 'Hashes cascade across blocks', 'Hash functions fail under load'], correct: 1, explanation: 'The avalanche effect means even a single character change produces a completely different hash output. This makes tampering immediately detectable.' },
      { id: 'q2', text: 'Why does DRP use CRYSTALS-Dilithium for signatures?', options: ['It\'s faster than SHA-256', 'It provides quantum-resistant digital signatures', 'It replaces blockchain entirely', 'It encrypts all user data'], correct: 1, explanation: 'CRYSTALS-Dilithium is a NIST-approved post-quantum signature scheme. DRP uses it to ensure transaction signatures remain secure even against future quantum computers.' },
    ]}
  },
  'consensus-mechanisms': {
    slug: 'consensus-mechanisms', title: 'Consensus Mechanisms',
    duration: '25m', reward: '20', xp: 40, level: 1,
    description: 'How distributed networks agree without a central authority.',
    prevSlug: 'cryptography-and-hashing', nextSlug: 'smart-contracts-101',
    content: `## The Problem of Distributed Agreement\n\nIn a decentralized network, there's no central authority to decide what's true. All nodes must independently reach the same conclusion — this is the consensus problem.\n\n## Major Consensus Types\n\n**Proof of Work (PoW)** — Used by Bitcoin. Nodes compete to solve a hard puzzle. Winner adds the next block. Secure but energy-intensive.\n\n**Proof of Stake (PoS)** — Used by Ethereum. Validators selected based on tokens they've locked. Much more efficient than PoW.\n\n## DRP's Hybrid Consensus\n\n\`\`\`\nLayer 1: Proof of Activity (PoAT)\n   ↓ verifies real human activity\nLayer 2: Proof of Status (PoST)\n   ↓ verifies rights holder status\nLayer 3: Elder Quorum Voting\n   ↓ AI-weighted final consensus (2/3 supermajority)\n\`\`\`\n\nThis makes DRP both **human-centered** and **Sybil-resistant** — bots can't fake real human activity.\n\n## Byzantine Fault Tolerance\n\nDRP's consensus is BFT — works correctly even if up to ⅓ of validators are malicious. The Elder Quorum requires a **2/3 supermajority** for finality.`,
    quiz: { questions: [
      { id: 'q1', text: 'What does "Sybil resistance" mean?', options: ['Resistance to cold', 'Prevention of fake identities flooding the network', 'A type of encryption', 'Quantum protection'], correct: 1, explanation: 'Sybil attacks involve creating many fake identities to manipulate a network. DRP\'s PoAT and PoST layers make this impossible since verified human activity is required.' },
      { id: 'q2', text: 'DRP requires what fraction of Elders to achieve finality?', options: ['Simple majority (50%+1)', '2/3 supermajority', '100% agreement', '⅓ quorum'], correct: 1, explanation: 'DRP requires a 2/3 supermajority — the classic Byzantine Fault Tolerance threshold, secure even if some Elders are compromised.' },
    ]}
  },
  'smart-contracts-101': {
    slug: 'smart-contracts-101', title: 'Smart Contracts 101',
    duration: '30m', reward: '25', xp: 50, level: 1,
    description: 'Self-executing code on the blockchain — the engine of DRP.',
    prevSlug: 'consensus-mechanisms', nextSlug: 'drp-architecture',
    content: `## What is a Smart Contract?\n\nA smart contract is self-executing code stored on a blockchain. It automatically enforces agreements when predefined conditions are met — no intermediaries required.\n\n\`\`\`\nTraditional: Party A → Lawyer → Court → Enforcement\nSmart Contract: Condition Met → Code Runs → Done\n\`\`\`\n\n## DRP's Smart Contract System\n\n| Contract | Purpose |\n|---|---|\n| **RightsVerifier** | Validates PoST and PoAT proofs |\n| **ElderRegistry** | Manages Elder Quorum membership |\n| **TokenDistributor** | Distributes $RIGHTS and $DeRi rewards |\n| **EvidenceVault** | Stores immutable rights violation records |\n| **GovernanceCore** | Processes Elder Quorum proposals |\n\n## Key Properties\n\nSmart contracts are **autonomous** (no human needed), **transparent** (code is public), **immutable** (can\'t change after deployment), and **deterministic** (same inputs → same outputs, always).\n\n## Security\n\nDRP\'s contracts undergo: internal code review, external security audit, post-quantum signature verification, and formal verification for critical paths.`,
    quiz: { questions: [
      { id: 'q1', text: 'What makes smart contracts "trustless"?', options: ['They are written by trusted developers', 'They execute automatically based on code with no intermediary', 'They use traditional legal frameworks', 'They are monitored by regulators'], correct: 1, explanation: 'Smart contracts execute exactly as written code dictates — no human intermediary can manipulate the outcome after deployment.' },
      { id: 'q2', text: 'Which DRP contract stores rights violation records immutably?', options: ['ElderRegistry', 'TokenDistributor', 'EvidenceVault', 'RightsVerifier'], correct: 2, explanation: 'The EvidenceVault stores immutable records of rights violations on-chain. Once stored, these records cannot be altered or deleted.' },
    ]}
  },
  'drp-architecture': {
    slug: 'drp-architecture', title: 'DRP Architecture',
    duration: '25m', reward: '20', xp: 40, level: 2,
    description: 'The full technical architecture of the Decentralized Rights Protocol.',
    prevSlug: 'smart-contracts-101', nextSlug: 'activity-proofs',
    content: `## System Overview\n\n\`\`\`\n┌─────────────────────────────────────┐\n│  Application Layer (dApps, Portal)  │\n├─────────────────────────────────────┤\n│  Protocol Layer (PoAT, PoST, Elders)│\n├─────────────────────────────────────┤\n│  Consensus Layer (Hybrid BFT)       │\n├─────────────────────────────────────┤\n│  Network Layer (P2P, OrbitDB, IPFS) │\n└─────────────────────────────────────┘\n\`\`\`\n\n## Core Components\n\n**1. Proof of Activity (PoAT) Engine** — Verifies that humans perform real-world activities. AI engine scores and anchors them on-chain.\n\n**2. Proof of Status (PoST) System** — Validates rights status combining identity verification, activity history, and AI scoring.\n\n**3. Elder Quorum** — Rotating high-trust validators selected by merit and cumulative PoAT/PoST scores. Vote on governance and validate blocks.\n\n**4. AI Governance Layer (Project LAZARUS)** — Monitors the network, scores participants, flags anomalies, manages digital testaments.\n\n**5. Quantum-Safe Cryptography** — All signatures use CRYSTALS-Kyber/Dilithium.\n\n## Data Flow\n\n\`\`\`\nUser Activity → PoAT verifies → AI scores\n    → PoST updates → Elder Quorum finalizes\n    → Block added → $DeRi reward distributed\n\`\`\``,
    quiz: { questions: [
      { id: 'q1', text: 'Which layer contains PoAT and PoST?', options: ['Application Layer', 'Protocol Layer', 'Consensus Layer', 'Network Layer'], correct: 1, explanation: 'PoAT and PoST are core protocol mechanisms that live in the Protocol Layer of DRP\'s architecture.' },
      { id: 'q2', text: 'What is Project LAZARUS in DRP?', options: ['A token', 'DRP\'s AI governance engine', 'A smart contract', 'The Explorer UI'], correct: 1, explanation: 'Project LAZARUS is DRP\'s autonomous AI agent that monitors the network, scores participants, flags anomalies, and manages digital testaments.' },
    ]}
  },
  'activity-proofs': {
    slug: 'activity-proofs', title: 'Activity Proofs (PoAT)',
    duration: '35m', reward: '30', xp: 60, level: 2,
    description: 'Deep dive into Proof of Activity — DRP\'s core human verification mechanism.',
    prevSlug: 'drp-architecture', nextSlug: 'post-poat-consensus',
    content: `## What is Proof of Activity?\n\nProof of Activity (PoAT) is DRP's core innovation — cryptographically verifying that a **real human performed a real-world activity**. Unlike PoW (computation) or PoS (capital), PoAT proves **human existence and action**.\n\n## The Activity Proof Lifecycle\n\n\`\`\`\n1. User performs activity (farming, voting, education...)\n2. Activity data captured (GPS, biometric, community witness)\n3. Zero-knowledge proof generated (privacy preserved)\n4. Proof submitted to DRP node\n5. AI engine validates + scores the proof\n6. Elder Quorum counter-signs (high-stakes activities)\n7. Activity record anchored on-chain\n8. $DeRi reward distributed to participant\n\`\`\`\n\n## Activity Categories\n\n| Category | Examples | Reward Multiplier |\n|---|---|---|\n| Essential | Food production, healthcare | 2.0x |\n| Civic | Voting, community service | 1.5x |\n| Educational | Learning, training | 1.3x |\n| Economic | Trade, labor | 1.0x |\n| Digital | Content creation, code | 0.8x |\n\n## Privacy: Prove Without Revealing\n\nDRP uses **zero-knowledge proofs (ZKPs)** so:\n- The activity can be verified without revealing private details\n- Location is proven without exposing exact coordinates\n- Identity is confirmed without exposing personal data`,
    quiz: { questions: [
      { id: 'q1', text: 'How does DRP protect privacy in activity proofs?', options: ['All data is public on-chain', 'Zero-knowledge proofs verify without revealing private details', 'Only Elders can see activity data', 'Activities are deleted after verification'], correct: 1, explanation: 'Zero-knowledge proofs allow DRP to mathematically verify that an activity occurred without the verifier learning any private details.' },
      { id: 'q2', text: 'Which activity category gets the highest reward multiplier?', options: ['Digital (content)', 'Economic (trade)', 'Essential (food, healthcare)', 'Educational (learning)'], correct: 2, explanation: 'Essential activities like food production and healthcare receive a 2.0x reward multiplier because they directly support human rights and basic needs.' },
    ]}
  },
  'post-poat-consensus': {
    slug: 'post-poat-consensus', title: 'Status Proofs (PoST)',
    duration: '25m', reward: '20', xp: 40, level: 2,
    description: 'Understanding Proof of Status and how it tracks rights over time.',
    prevSlug: 'activity-proofs', nextSlug: 'elder-quorum-system',
    content: `## What is Proof of Status?\n\nProof of Status (PoST) is a continuously updated, on-chain record of an individual's rights status, computed from cumulative PoAT history, community standing, and AI-assessed scores. Think of it as a **living, verifiable rights passport** — earned through verified activity, not issued by any government.\n\n## PoST Score Components\n\n| Component | Weight |\n|---|---|\n| Activity History | 40% |\n| Community Verification | 25% |\n| AI Assessment | 20% |\n| Temporal Consistency | 15% |\n\n## PoST Status Levels\n\n\`\`\`\nUNVERIFIED → PENDING → ACTIVE → ELDER-ELIGIBLE\n\`\`\`\n\n- **UNVERIFIED**: No PoAT records yet\n- **PENDING**: Has some PoAT, under AI review\n- **ACTIVE**: Verified rights holder — can vote, earn, use DRP services\n- **ELDER-ELIGIBLE**: High-trust, long-term verified — eligible for Elder Quorum`,
    quiz: { questions: [
      { id: 'q1', text: 'What is the highest PoST status a user can reach?', options: ['ACTIVE', 'ELDER-ELIGIBLE', 'VERIFIED', 'GOLD'], correct: 1, explanation: 'ELDER-ELIGIBLE is the highest PoST status, indicating a high-trust long-term participant who can join the Elder Quorum.' },
      { id: 'q2', text: 'What contributes the most to a user\'s PoST score?', options: ['Community verification (25%)', 'AI assessment (20%)', 'Activity history (40%)', 'Temporal consistency (15%)'], correct: 2, explanation: 'Activity history from PoAT records carries 40% of the PoST score — the largest component, grounding PoST in real-world human activity.' },
    ]}
  },
  'elder-quorum-system': {
    slug: 'elder-quorum-system', title: 'Elder Quorum System',
    duration: '30m', reward: '25', xp: 50, level: 2,
    description: 'How the Elder Quorum governs and secures DRP.',
    prevSlug: 'post-poat-consensus', nextSlug: 'drp-development-kit',
    content: `## What are Elders?\n\nElders are DRP's highest-trust validators — selected from participants who have achieved ELDER-ELIGIBLE PoST status. They are selected by **merit and verified human activity**, NOT by holding tokens.\n\n## Elder Responsibilities\n\n1. **Block Validation** — Co-sign new blocks (2/3 supermajority required)\n2. **Governance Voting** — Vote on protocol upgrades and parameter changes\n3. **Dispute Resolution** — Arbitrate contested PoAT/PoST records\n4. **Emergency Response** — Coordinate emergency protocol actions\n5. **AI Oversight** — Review and challenge AI engine decisions\n\n## Quorum Structure\n\n\`\`\`\nElder Quorum (~100 rotating members)\n├── Regional Seats (by geography)\n├── Domain Seats (healthcare, agriculture, education...)\n└── At-Large Seats (top PoST scorers globally)\n\`\`\`\n\n## Becoming an Elder\n\n- ELDER-ELIGIBLE PoST status required\n- 12+ months of continuous PoAT activity\n- Pass a governance knowledge assessment\n- Nomination by existing Elders or community vote\n- 6-month terms, maximum 3 consecutive terms`,
    quiz: { questions: [
      { id: 'q1', text: 'How are Elders selected in DRP?', options: ['By holding the most $RIGHTS tokens', 'By merit and verified human activity (PoST eligibility)', 'By a vote from the founding team', 'By random lottery'], correct: 1, explanation: 'Unlike token-based PoS systems, DRP Elders are selected based on merit — achieving ELDER-ELIGIBLE PoST status through a long history of verified real-world activity.' },
      { id: 'q2', text: 'What fraction of Elders is required to validate a block?', options: ['Simple majority (50%+1)', '2/3 supermajority', 'All Elders (100%)', 'Any single Elder'], correct: 1, explanation: 'A 2/3 supermajority is required — the Byzantine Fault Tolerance threshold that guarantees safety even if up to 1/3 of Elders are compromised.' },
    ]}
  },
  'drp-development-kit': {
    slug: 'drp-development-kit', title: 'DRP Development Kit',
    duration: '30m', reward: '25', xp: 50, level: 3,
    description: 'Start building on DRP with the official SDK.',
    prevSlug: 'elder-quorum-system', nextSlug: 'building-dapps',
    content: `## Getting Started\n\n\`\`\`bash\nnpm install @drp/sdk\n\`\`\`\n\n## Connect to DRP\n\n\`\`\`typescript\nconst drp = new DRPClient({\n  network: 'testnet',\n  endpoint: 'https://api.decentralizedrights.com',\n})\n\`\`\`\n\n## Submit an Activity Proof\n\n\`\`\`typescript\nconst result = await new ActivityProver(drp).submit({\n  activityType: 'education',\n  metadata: { course: 'blockchain-fundamentals', score: 0.95 },\n  timestamp: Date.now(),\n})\nconsole.log(result.txHash)      // On-chain transaction\nconsole.log(result.deriReward)  // $DeRi earned\nconsole.log(result.xpGained)    // XP added to profile\n\`\`\`\n\n## Check Rights Status\n\n\`\`\`typescript\nconst status = await new StatusChecker(drp).getStatus(walletAddress)\n// Returns: { level: 'ACTIVE', score: 0.87, eligible: true }\n\`\`\`\n\n## Key Rules\n\n1. Always use **testnet** when developing\n2. Never hardcode private keys in frontend code\n3. Cache PoST results to avoid hammering the RPC endpoint\n4. Handle network errors gracefully — blockchains can be slow`,
    quiz: { questions: [
      { id: 'q1', text: 'What network should you use when developing?', options: ['mainnet', 'testnet', 'devnet', 'localhost'], correct: 1, explanation: 'Always use testnet when developing. Test $DeRi has no real value so you can freely experiment.' },
      { id: 'q2', text: 'What does ActivityProver.submit() return?', options: ['Just a transaction hash', 'A txHash, deriReward, and xpGained', 'A boolean success flag', 'The updated PoST score'], correct: 1, explanation: 'submit() returns a rich result object including the on-chain txHash, $DeRi earned, and XP added to the profile.' },
    ]}
  },
  'building-dapps': { slug: 'building-dapps', title: 'Building DApps on DRP', duration: '40m', reward: '35', xp: 70, level: 3, description: 'Build decentralized applications integrated with DRP proofs.', prevSlug: 'drp-development-kit', nextSlug: 'contributing-to-drp', content: `## Architecture\n\n\`\`\`\nFrontend (Next.js) \u21d5 DRP SDK \u21d5 DRP Protocol \u21d5 Blockchain\n\`\`\`\n\n## Gate Features by Rights Status\n\n\`\`\`typescript\nasync function requireActiveStatus(userAddress: string) {\n  const status = await new StatusChecker(drp).getStatus(userAddress)\n  if (status.level !== 'ACTIVE') throw new Error('DRP verification required')\n  return status\n}\n\`\`\`\n\n## Best Practices\n\n1. Never store private keys in frontend code\n2. Handle network errors gracefully\n3. Display proof status clearly in your UI\n4. Use testnet throughout development\n5. Cache PoST results to avoid hammering the RPC`, quiz: { questions: [{ id: 'q1', text: 'Where should private keys be stored?', options: ['Frontend JavaScript', 'localStorage', 'A secure backend signing service', 'Env vars in the frontend'], correct: 2, explanation: 'Private keys must never be exposed in frontend code. Use a backend signing service that signs transactions server-side.' }] } },
  'contributing-to-drp': { slug: 'contributing-to-drp', title: 'Contributing to DRP', duration: '25m', reward: '20', xp: 40, level: 3, description: 'How to contribute code, docs, and ideas to DRP.', prevSlug: 'building-dapps', nextSlug: 'testing-and-deployment', content: `## Ways to Contribute\n\n- **Code**: Protocol improvements, bug fixes, new features\n- **Documentation**: Guides, tutorials, whitepaper improvements\n- **Testing**: Finding bugs, writing tests, security audits\n- **Community**: Translations, educational content, outreach\n\n## Contribution Rewards\n\n| Contribution | $DeRi |\n|---|---|\n| Bug fix (merged) | 50 |\n| Feature (merged) | 150 |\n| Security fix | 500 |\n| Documentation | 25 |`, quiz: { questions: [{ id: 'q1', text: 'What PoAT category do code contributions fall under?', options: ['Essential', 'Economic', 'Educational', 'Civic'], correct: 3, explanation: 'Code contributions to DRP are Civic activity in PoAT, reflecting their role in building public digital infrastructure.' }] } },
  'testing-and-deployment': { slug: 'testing-and-deployment', title: 'Testing & Deployment', duration: '35m', reward: '30', xp: 60, level: 3, description: 'Best practices for testing and deploying DRP applications.', prevSlug: 'contributing-to-drp', nextSlug: 'identity-access-management', content: `## Testing Strategy\n\n\`\`\`\nUnit Tests \u2192 Integration Tests \u2192 E2E Tests \u2192 Testnet \u2192 Mainnet\n\`\`\`\n\n## Testnet Deployment Checklist\n\n- [ ] All unit tests passing\n- [ ] Private keys in environment variables (never hardcoded)\n- [ ] Error handling for RPC timeouts\n- [ ] Rate limiting implemented\n- [ ] PoST status checking before gated actions\n\n## Production\n\nDRP apps deploy anywhere. Recommended: **Vercel/Netlify** for Next.js frontends, **Render/Railway** for backend APIs.`, quiz: { questions: [{ id: 'q1', text: 'What should you use for testing without real consequences?', options: ['DRP mainnet', 'MockDRPClient and testnet', 'Production data with test flag', 'Any Ethereum testnet'], correct: 1, explanation: 'MockDRPClient lets you unit test without any network connection. The DRP testnet lets you do integration testing without spending real tokens.' }] } },
  'identity-access-management': { slug: 'identity-access-management', title: 'Identity & Access Management', duration: '30m', reward: '25', xp: 50, level: 4, description: 'DRP as a foundation for decentralized, rights-based identity.', prevSlug: 'testing-and-deployment', nextSlug: 'supply-chain-applications', content: `## DRP as a Rights-Based Identity Layer\n\nTraditional identity relies on central authorities. DRP creates a parallel system where identity is **earned through verified activity** and owned by the individual.\n\n## DRP Identity vs Traditional\n\n| Feature | Traditional | DRP |\n|---|---|---|\n| Issued by | Government/corp | Earned through activity |\n| Revocable | Yes, unilaterally | Only through governance |\n| Privacy | Often exposed | Zero-knowledge by default |\n| Portable | No | Universal across DRP |\n| Quantum-safe | No | Yes (CRYSTALS) |`, quiz: { questions: [{ id: 'q1', text: 'How is DRP identity different from a government ID?', options: ['DRP IDs expire after 10 years', 'DRP identity is earned through activity, not issued by any authority', 'DRP IDs cost more', 'DRP IDs require a photo'], correct: 1, explanation: 'DRP identity is earned through verified human activity (PoAT) — not issued by a central authority. This makes it censorship-resistant and self-sovereign.' }] } },
  'supply-chain-applications': { slug: 'supply-chain-applications', title: 'Supply Chain Applications', duration: '35m', reward: '30', xp: 60, level: 4, description: 'Using DRP to bring verifiable transparency to supply chains.', prevSlug: 'identity-access-management', nextSlug: 'cross-chain-interoperability', content: `## The Problem\n\nGlobal supply chains often hide child labor, unsafe conditions, and fraudulent certifications. Consumers have no reliable way to verify claims.\n\n## DRP's Solution: Ghana Cocoa Example\n\n\`\`\`\nFarmer Kofi harvests cocoa \u2192 PoAT submitted (GPS-verified)\n    \u2192 Co-op adds attestation\n    \u2192 Exporter shipment verified\n    \u2192 Manufacturer scans on delivery\n    \u2192 Consumer scans QR \u2192 sees full verified chain on DRP\n\`\`\`\n\nEvery step is a verified PoAT record. No document can be faked.`, quiz: { questions: [{ id: 'q1', text: 'How does DRP prevent fake certifications in supply chains?', options: ['Encrypting all supply chain data', 'Every step is a verified PoAT record that can\'t be forged', 'Using paper audits', 'Requiring government approval'], correct: 1, explanation: 'Each supply chain step must be submitted as a PoAT proof by a verified DRP participant. These immutable records can\'t be forged without controlling the participant\'s private key.' }] } },
  'cross-chain-interoperability': { slug: 'cross-chain-interoperability', title: 'Cross-Chain Interoperability', duration: '40m', reward: '35', xp: 70, level: 4, description: 'How DRP connects with other blockchains and protocols.', prevSlug: 'supply-chain-applications', nextSlug: 'enterprise-integration', content: `## DRP's Interoperability Stack\n\n\`\`\`\nDRP Chain\n    \u21d5 IBC (Inter-Blockchain Communication)\nCosmos Ecosystem\n    \u21d5 Bridge Contracts\nEthereum, Polygon, BNB Chain\n\`\`\`\n\nYour DRP PoST status can be exported as a Verifiable Credential and used on other chains.`, quiz: { questions: [{ id: 'q1', text: 'What protocol connects DRP to the Cosmos ecosystem?', options: ['Chainlink', 'IBC (Inter-Blockchain Communication)', 'LayerZero', 'Polkadot XCMP'], correct: 1, explanation: 'DRP uses IBC to connect with the Cosmos ecosystem, enabling trustless cross-chain messaging.' }] } },
  'enterprise-integration': { slug: 'enterprise-integration', title: 'Enterprise Integration', duration: '35m', reward: '40', xp: 80, level: 4, description: 'Integrating DRP into enterprise and NGO workflows.', prevSlug: 'cross-chain-interoperability', nextSlug: 'advanced-drp-concepts', content: `## Enterprise Use Cases\n\n| Sector | Use Case |\n|---|---|\n| Agriculture | Fair labor verification |\n| Healthcare | Patient rights and consent |\n| Finance | KYC with privacy, unbanked inclusion |\n| Government | Transparent aid distribution |\n| NGOs | Beneficiary verification without ID documents |\n\n## Privacy\n\n\`\`\`\nEnterprise asks: "Is this worker verified?"\nDRP answers: "Yes/No" (cryptographic proof)\nPersonal data: Never exposed\n\`\`\``, quiz: { questions: [{ id: 'q1', text: 'How does DRP handle enterprise data privacy?', options: ['All data is public', 'ZKPs allow yes/no verification without exposing personal data', 'Enterprises get full access to profiles', 'A third party mediates all queries'], correct: 1, explanation: 'Zero-knowledge proofs let enterprises verify rights status without DRP revealing any personal data. Full privacy, full compliance.' }] } },
  'advanced-drp-concepts': { slug: 'advanced-drp-concepts', title: 'Advanced DRP Concepts', duration: '45m', reward: '50', xp: 100, level: 5, description: 'Deep technical concepts for protocol researchers and contributors.', prevSlug: 'enterprise-integration', nextSlug: 'economic-models', content: `## Project LAZARUS: AI Elder System\n\nLAZARUS is DRP's autonomous AI agent network that scans for lost wallets, detects anomalies, advises the Elder Quorum, and manages digital testaments.\n\n## Zero-Knowledge Proof System\n\nDRP uses **zk-SNARKs**:\n\n\`\`\`\nProver has: secret activity data + witness\nVerifier sees: only the proof (~200 bytes)\nResult: 100% certainty activity occurred, zero private data revealed\n\`\`\`\n\n## Quantum Threat Model\n\n| Algorithm | Quantum Threat | DRP Response |\n|---|---|---|\n| ECDSA | Broken by Shor's algorithm | Replaced by Dilithium |\n| SHA-256 | Weakened (Grover's) | Using SHA3-256 |\n| AES-256 | Minimally affected | Still used (symmetric) |`, quiz: { questions: [{ id: 'q1', text: 'What cryptographic primitive does DRP use for privacy-preserving proofs?', options: ['RSA signatures', 'zk-SNARKs', 'Traditional hash commitments', 'Homomorphic encryption'], correct: 1, explanation: 'DRP uses zk-SNARKs for activity proof privacy — proving knowledge of secret data without revealing the data, with tiny fast-to-verify proofs.' }, { id: 'q2', text: 'Why did DRP replace ECDSA with Dilithium?', options: ['Dilithium is faster', 'ECDSA can be broken by quantum computers via Shor\'s algorithm', 'Dilithium uses smaller keys', 'ECDSA was never secure'], correct: 1, explanation: 'Shor\'s algorithm running on a quantum computer can break ECDSA. CRYSTALS-Dilithium is designed to resist quantum attacks.' }] } },
  'economic-models': { slug: 'economic-models', title: 'Economic Models', duration: '40m', reward: '45', xp: 90, level: 5, description: 'The token economics and incentive design of DRP.', prevSlug: 'advanced-drp-concepts', nextSlug: 'governance-mechanisms', content: `## The Dual-Token System\n\n**$RIGHTS** — Governance token. Non-transferable by default (prevents plutocracy). Earned through long-term verified activity.\n\n**$DeRi** — Utility token. Tradeable. Earned for every verified PoAT activity.\n\n## Token Emission\n\n\`\`\`\nYear 1-2: High emission (bootstrap adoption)\nYear 3-5: Moderate emission (growth phase)\nYear 6+:  Low emission (maturity / deflationary)\n\`\`\`\n\nDRP's economy is fundamentally **labor-backed** rather than capital-backed. 5% of all emissions go to the Sustainability Reserve (SRE), governed by Elders.`, quiz: { questions: [{ id: 'q1', text: 'What makes $RIGHTS different from $DeRi?', options: ['$RIGHTS is tradeable, $DeRi is not', '$RIGHTS is governance (non-transferable by default), $DeRi is utility (tradeable)', 'They are identical', '$DeRi can only be used to vote'], correct: 1, explanation: '$RIGHTS is governance — non-transferable by default to prevent plutocracy. $DeRi is utility — tradeable and earned for every activity.' }] } },
  'governance-mechanisms': { slug: 'governance-mechanisms', title: 'Governance Mechanisms', duration: '35m', reward: '50', xp: 100, level: 5, description: 'How DRP governance works at the protocol level.', prevSlug: 'economic-models', nextSlug: 'future-of-drp', content: `## Philosophy\n\nDRP's principle: **those most affected by decisions should have the most say**. Active, verified participants govern — not passive token holders.\n\n## Proposal Types\n\n| Type | Required |\n|---|---|\n| Parameter Change | Elder simple majority |\n| Protocol Upgrade | 2/3 supermajority |\n| Emergency Action | 3/4 + AI confirmation |\n| Constitutional | 4/5 + community vote |\n\n## Proposal Lifecycle\n\n\`\`\`\nDraft \u2192 Discussion (7 days) \u2192 Elder Review\n    \u2192 Voting (7 days) \u2192 Timelock (48h) \u2192 Execution\n\`\`\``, quiz: { questions: [{ id: 'q1', text: 'How long is the mandatory timelock before execution?', options: ['24 hours', '48 hours', '7 days', '30 days'], correct: 1, explanation: 'A 48-hour timelock is mandatory between a vote passing and on-chain execution — giving the community time to respond if a malicious proposal passed.' }] } },
  'future-of-drp': { slug: 'future-of-drp', title: 'The Future of DRP', duration: '30m', reward: '55', xp: 110, level: 5, description: 'DRP\'s roadmap and long-term vision for human rights infrastructure.', prevSlug: 'governance-mechanisms', content: `## Vision\n\nDRP's mission: become the global verification layer for human rights — neutral, decentralized, quantum-safe, for everyone.\n\n## Near-Term Roadmap (2025–2026)\n\n- ✅ Core protocol design and whitepaper\n- ✅ Testnet deployment with working API\n- 🔄 Elder Quorum pilot — Ghana, Nigeria, Kenya\n- 🔄 DRP Learn platform (you're on it!)\n- ⏳ $DeRi token launch on testnet\n- ⏳ First enterprise partnerships\n\n## Long-Term Goals (by 2035)\n\n- **2B+ verified humans** with on-chain rights status\n- **Zero unbanked**: DRP identity enables global financial access\n- **Supply chain transparency** for top 100 global corporations\n- **Legal precedent**: DRP evidence accepted in international courts\n\n## How You Can Shape DRP's Future\n\n1. **Build** — Use the DRP SDK\n2. **Contribute** — Submit code, docs, or research\n3. **Govern** — Earn your path to Elder eligibility\n4. **Spread** — Educate communities about rights infrastructure\n5. **Verify** — Submit your own activity proofs and earn $DeRi`, quiz: { questions: [{ id: 'q1', text: 'What is DRP\'s long-term goal for verified users?', options: ['10 million by 2026', '2 billion verified humans with on-chain rights status by 2035', '100,000 Elder validators', '50 enterprise partnerships'], correct: 1, explanation: 'DRP\'s long-term vision is 2B+ verified humans with on-chain rights status by 2035 — making DRP the global verification layer for human rights.' }, { id: 'q2', text: 'Which region is targeted for DRP\'s first Elder Quorum pilot?', options: ['Silicon Valley', 'Southeast Asia', 'Africa (Ghana, Nigeria, Kenya)', 'Europe'], correct: 2, explanation: 'DRP\'s first Elder Quorum pilot targets Africa — specifically Ghana, Nigeria, and Kenya — reflecting the mission to serve underserved populations first.' }] } },
}
