export const metadata = { title: 'Terms of Service | DRP Portal', description: 'Terms governing use of the Decentralized Rights Protocol Portal.' }

export default function TermsPage() {
  return <article className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
    <p className="text-xs font-bold uppercase tracking-[.2em] text-[#00e5cc]">Legal</p>
    <h1 className="mt-3 text-4xl font-black tracking-tight">Terms of Service</h1>
    <p className="mt-3 text-sm text-white/50">Last updated: 7 September 2026</p>
    <div className="mt-10 space-y-8 text-sm leading-7 text-white/75">
      <section><h2 className="text-xl font-bold text-white">1. Agreement</h2><p className="mt-3">These Terms govern access to and use of the DRP Portal. By using the Portal, you agree to these Terms and the Privacy Policy. If you do not agree, do not use the service.</p></section>
      <section><h2 className="text-xl font-bold text-white">2. What DRP provides</h2><p className="mt-3">The Portal provides software for submitting, viewing and verifying activity or status claims and interacting with DRP infrastructure. Features may change, be unavailable, or remain in testing. Descriptions of planned protocol capabilities are not promises that a feature is currently available.</p></section>
      <section><h2 className="text-xl font-bold text-white">3. No guarantee of verification or rewards</h2><p className="mt-3">Submitting a proof does not guarantee approval, verification, eligibility, rewards, token value, governance rights, or any particular outcome. Verification decisions may depend on protocol rules, evidence quality, network availability and applicable governance processes.</p></section>
      <section><h2 className="text-xl font-bold text-white">4. Wallets and blockchain transactions</h2><p className="mt-3">You are responsible for your wallet, device, credentials and transaction approvals. DRP will never ask you to disclose a private key or seed phrase. Blockchain transactions can be irreversible and may incur network fees. Confirm transaction details before signing.</p></section>
      <section><h2 className="text-xl font-bold text-white">5. User submissions</h2><p className="mt-3">You must have the right to submit any text, files, images, video or other evidence you provide. Do not upload another person's private information without a lawful basis and appropriate permission. Do not submit unlawful, fraudulent, defamatory, infringing, malicious or abusive material.</p></section>
      <section><h2 className="text-xl font-bold text-white">6. Intellectual property</h2><p className="mt-3">DRP software, branding, documentation and content are protected by applicable intellectual-property laws unless a specific licence states otherwise. You retain rights you already have in your submissions, subject to the permissions needed to operate verification and display features.</p></section>
      <section><h2 className="text-xl font-bold text-white">7. Prohibited conduct</h2><p className="mt-3">Do not attempt to compromise the Portal, bypass access controls, submit fabricated evidence, manipulate verification, abuse rewards, impersonate another person, upload malware, or use the service in violation of applicable law.</p></section>
      <section><h2 className="text-xl font-bold text-white">8. Disclaimers</h2><p className="mt-3">The Portal is provided on an availability basis. DRP does not guarantee uninterrupted operation, error-free verification, blockchain finality, or absolute security. Nothing on the Portal is legal, financial, investment, medical or human-rights legal advice.</p></section>
      <section><h2 className="text-xl font-bold text-white">9. Suspension and termination</h2><p className="mt-3">Access may be restricted where reasonably necessary to protect users, the network, evidence integrity, or comply with law. Where appropriate, users will be given notice and an opportunity to resolve the issue.</p></section>
      <section><h2 className="text-xl font-bold text-white">10. Governing law</h2><p className="mt-3">These Terms are intended to operate consistently with applicable Ghanaian law, including the Electronic Transactions Act, 2008 (Act 772), and mandatory consumer, privacy and other protections that apply to a particular user or transaction. Mandatory rights are not excluded by these Terms.</p></section>
      <section><h2 className="text-xl font-bold text-white">11. Contact</h2><p className="mt-3">Questions about these Terms should be sent to <a className="text-[#00e5cc] underline" href="mailto:contact@decentralizedrights.com">contact@decentralizedrights.com</a>.</p></section>
    </div>
  </article>
}
