export const metadata = { title: 'Privacy Policy | DRP Portal', description: 'How the Decentralized Rights Protocol Portal collects, uses, protects, and shares personal data.' }

export default function PrivacyPage() {
  return <article className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
    <p className="text-xs font-bold uppercase tracking-[.2em] text-[#00e5cc]">Legal</p>
    <h1 className="mt-3 text-4xl font-black tracking-tight">Privacy Policy</h1>
    <p className="mt-3 text-sm text-white/50">Last updated: 7 September 2026</p>
    <div className="mt-10 space-y-8 text-sm leading-7 text-white/75">
      <section><h2 className="text-xl font-bold text-white">1. Who operates the Portal</h2><p className="mt-3">The service is operated under the name Decentralized Rights Protocol (DRP). The public contact address for privacy and service questions is <a className="text-[#00e5cc] underline" href="mailto:contact@decentralizedrights.com">contact@decentralizedrights.com</a>. If DRP is later operated by a registered legal entity, this notice should be updated with that entity’s legal name, registered address and applicable registration details.</p></section>
      <section><h2 className="text-xl font-bold text-white">2. Data we collect</h2><p className="mt-3">We aim to collect only data needed to provide and secure the Portal. Depending on the feature you use, this may include a wallet/public address, activity or proof information you submit, evidence files you choose to upload, transaction or verification identifiers, basic account/contact information when you voluntarily provide it, and technical/security information needed to operate the service.</p><p className="mt-3">Do not submit passwords, private keys, seed phrases, government identification numbers, health information, or other sensitive information unless a feature explicitly requests it and the applicable notice explains why it is needed.</p></section>
      <section><h2 className="text-xl font-bold text-white">3. Why we use it</h2><p className="mt-3">We use information to authenticate and secure access, process proof submissions, provide verification and rewards features, prevent abuse, maintain audit and security records, provide support, and meet legal obligations. We do not sell personal data.</p></section>
      <section><h2 className="text-xl font-bold text-white">4. Blockchain and decentralized records</h2><p className="mt-3">Some records may be written to blockchain, decentralized storage or other distributed systems. Such records can be difficult or impossible to alter or delete after publication. You should not submit personal information that you do not want associated with a potentially persistent public record. Where possible, DRP should use hashes, identifiers and minimised data rather than unnecessary personal information.</p></section>
      <section><h2 className="text-xl font-bold text-white">5. Service providers</h2><p className="mt-3">The Portal may use infrastructure providers such as Vercel, Convex, Render, Storacha/IPFS, wallet providers and blockchain/network infrastructure. They may process information on DRP’s behalf or as independent providers. Their own terms and privacy notices may also apply.</p></section>
      <section><h2 className="text-xl font-bold text-white">6. Retention and security</h2><p className="mt-3">We retain information only for as long as reasonably necessary for the stated purpose, security, dispute handling and legal obligations. We use access controls, encryption in transit and other reasonable safeguards, but no online system can be guaranteed completely secure.</p></section>
      <section><h2 className="text-xl font-bold text-white">7. Your rights</h2><p className="mt-3">Depending on applicable law, you may have rights to access, correct, delete, restrict or object to certain processing, and to withdraw consent where consent is the legal basis. Some rights may be limited where information is required for security, legal compliance, or has already been irreversibly committed to a decentralized network.</p></section>
      <section><h2 className="text-xl font-bold text-white">8. Ghana data protection</h2><p className="mt-3">DRP is designed with Ghana’s Data Protection Act, 2012 (Act 843) in mind. Where Ghana data-protection obligations apply, processing should be fair, lawful, transparent and limited to necessary purposes. The Ghana Data Protection Commission is the relevant regulator.</p></section>
      <section><h2 className="text-xl font-bold text-white">9. International processing</h2><p className="mt-3">Infrastructure providers may process data outside Ghana. Where applicable law requires safeguards for international transfers, DRP will use appropriate contractual, technical or other safeguards.</p></section>
      <section><h2 className="text-xl font-bold text-white">10. Contact</h2><p className="mt-3">For privacy requests or questions, email <a className="text-[#00e5cc] underline" href="mailto:contact@decentralizedrights.com">contact@decentralizedrights.com</a>.</p></section>
    </div>
  </article>
}
